version: "3.8"

services:
  database:
    container_name: pg_database
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_imoney_db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
